# Generated by Django 5.1.6 on 2025-02-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_healthvital_exang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthvital',
            name='exang',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthvital',
            name='rest_ecg',
            field=models.FloatField(),
        ),
    ]
