# Generated by Django 5.1.6 on 2025-02-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthvital',
            name='exang',
            field=models.IntegerField(),
        ),
    ]
