# Generated by Django 5.1.6 on 2025-03-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthvital',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
