# Generated by Django 5.1.6 on 2025-03-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_healthvital_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthvital',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
